name: CD


on:
  push:
    branches: [ main ]


env:
  DOTNET_VERSION: '8.0.x'
  DOCKERHUB_USERNAME: mohamedamin1996
  IMAGE_NAME: mohamedamin1996/todoapi


jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
